#!/usr/bin/python3
"""Factorize given set of numbers in a file to a product of two smaller numbers"""
import sys


def factorize(number_to_check):
    """Find two small numbers that multiply to give a given number"""
    for i in range(2, int(number_to_check / 2) + 1):
        if number_to_check % i == 0:
            print("{:.0f}={:.0f}*{:.0f}".format(number_to_check, i, number_to_check / i))
            break


if len(sys.argv) != 2:
    sys.exit()

try:
    with open(sys.argv[1]) as file:
        for line in file:
            number_to_check = int(line.strip())
            factorize(number_to_check)
except FileNotFoundError:
    print("File not found:", sys.argv[1], file=sys.stderr)
except ValueError:
    print("Invalid number in the file:", line.strip(), file=sys.stderr)
except:
    print("An error occurred while processing the file.", file=sys.stderr)
